#!/usr/bin/env bash
# review-bundle.sh — build a self-contained bundle for an adversarial reviewer that must NOT read
# the working tree.
#
# WHY
# ---
# The standing reviewer here (advocatus-diaboli) has no Bash and reads files. Its worktree is
# whatever the repository happens to be checked out at while it runs — in a session that keeps
# working, that is usually a different branch, so anything it Reads from the tree is pre-change
# or unrelated (memory: feedback_worktree_isolation_is_not_your_branch). The remedy that worked
# on 2026-09-02, twice, was a bundle in the scratchpad: the diff, full copies of every new or
# changed source file, the PR body, and a README telling the reviewer to read nothing else.
# Building that by hand each time is the calculation this tool replaces.
#
# A mirror-heavy change (165 one-line i18n hunks) drowns the review in noise, so paths matching
# a --summarise glob are reported as a stat plus a small sample instead of expanded hunks.
#
# USAGE
#     tools/review-bundle.sh [--base REF] [--out DIR] [--summarise GLOB]... [--body FILE] [--sample N]
#     tools/review-bundle.sh --verify        self-test in a throwaway repo; exit non-zero if the bundle
#                                            would omit a changed file or expand a summarised one
#
#   --base REF        diff base (default origin/main). The diff is REF...HEAD (merge-base form).
#   --out DIR         bundle directory (default: a fresh mktemp -d). Printed on the last line.
#   --summarise GLOB  git pathspec whose hunks are summarised, not expanded (repeatable).
#   --body FILE       PR body to include as pr-body.md.
#   --sample N        how many summarised files get their diff shown as a sample (default 3).
#
# EXIT: 0 bundle written; 1 --verify failed; 2 could not run (not a git repo, base unknown,
# no changes). 2 is never a pass.
set -uo pipefail

SELF="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

die() { printf 'review-bundle: %s\n' "$*" >&2; exit 2; }

build() {
  local base="origin/main" out="" body="" sample=3
  local -a summarise=()
  while [ $# -gt 0 ]; do
    case "$1" in
      --base) base="$2"; shift 2 ;;
      --out) out="$2"; shift 2 ;;
      --summarise) summarise+=("$2"); shift 2 ;;
      --body) body="$2"; shift 2 ;;
      --sample) sample="$2"; shift 2 ;;
      *) die "unknown argument: $1" ;;
    esac
  done
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not inside a git repository"
  git rev-parse --verify --quiet "$base^{commit}" >/dev/null || die "base ref not found: $base"
  [ -z "$out" ] && out="$(mktemp -d)"
  mkdir -p "$out" || die "cannot create $out"

  local -a excl=()
  local g
  for g in "${summarise[@]+"${summarise[@]}"}"; do excl+=(":(exclude)$g"); done

  local range="$base...HEAD"
  local changed
  changed="$(git diff --name-status "$range" -- .)"
  [ -n "$changed" ] || die "no changes between $base and HEAD"

  {
    printf '# Review bundle — diff %s\n\n' "$range"
    printf 'Generated by tools/review-bundle.sh. Source files in full; summarised paths as stat + sample.\n\n'
    printf '## Changed files (name-status)\n\n```\n%s\n```\n\n' "$changed"
    printf '## Diff of expanded paths\n\n```diff\n'
    git diff "$range" -- . "${excl[@]+"${excl[@]}"}"
    printf '```\n'
    if [ ${#summarise[@]} -gt 0 ]; then
      printf '\n## Summarised paths (%s)\n\n' "${summarise[*]}"
      printf '### stat\n\n```\n'
      git diff --stat "$range" -- "${summarise[@]}"
      printf '```\n\n### sample of %s file(s)\n\n```diff\n' "$sample"
      git diff --name-only "$range" -- "${summarise[@]}" | head -n "$sample" | while IFS= read -r f; do
        git diff "$range" -- "$f"
      done
      printf '```\n'
    fi
  } > "$out/diff.md"

  # Full copies: every added or modified file that is NOT summarised, at its post-change content.
  local status path
  mkdir -p "$out/files"
  while IFS=$'\t' read -r status path; do
    [ -n "$path" ] || continue
    case "$status" in A*|M*|R*|C*) ;; *) continue ;; esac
    for g in "${summarise[@]+"${summarise[@]}"}"; do
      case "$path" in $g) continue 2 ;; esac
    done
    mkdir -p "$out/files/$(dirname "$path")"
    git show "HEAD:$path" > "$out/files/$path" 2>/dev/null || cp "$path" "$out/files/$path"
  done <<< "$(git diff --name-status "$range" -- . | awk -F'\t' '{print $1 "\t" $NF}')"

  [ -n "$body" ] && cp "$body" "$out/pr-body.md"

  {
    printf '# Review bundle\n\n'
    printf 'Everything the reviewer needs is under this directory. **Do NOT read the repository working tree**'
    printf ' — it may be checked out on another branch while you work; anything read there can be pre-change or unrelated.\n\n'
    printf -- '- `diff.md` — the change (`%s`), expanded except for summarised paths\n' "$range"
    printf -- '- `files/<path>` — full post-change content of every added or modified source file\n'
    [ -n "$body" ] && printf -- '- `pr-body.md` — the PR body and its evidence claims\n'
    printf -- '- write your findings to `findings.md` in this directory (the file is the deliverable)\n\n'
    printf '## Files in this bundle\n\n```\n'
    (cd "$out" && find . -type f | sort)
    printf '```\n'
  } > "$out/README.md"

  printf 'bundle: %s\n' "$out"
  (cd "$out" && find . -type f | sort | sed 's/^/  /')
  printf '%s\n' "$out"
}

verify() {
  local tmp; tmp="$(mktemp -d)"
  local repo="$tmp/repo" out="$tmp/bundle" rc=0
  mkdir -p "$repo/i18n/de" "$repo/src"
  (
    cd "$repo" || exit 2
    git init -q && git config user.email t@t && git config user.name t
    printf 'one\ntwo\n' > src/a.txt; printf 'mirror\n' > i18n/de/x.md
    git add -A && git commit -qm base
    git branch -q base
    printf 'one\nTWO\n' > src/a.txt; printf 'new\n' > src/b.txt; printf 'mirror-changed\n' > i18n/de/x.md
    git add -A && git commit -qm change
    bash "$SELF" --base base --out "$out" --summarise 'i18n/*' >/dev/null
  ) || rc=$?
  [ "$rc" -eq 0 ] || { printf 'verify: build exited %s\n' "$rc"; rm -rf "$tmp"; exit 1; }

  check() { if eval "$2"; then printf '  ok   %s\n' "$1"; else printf '  FAIL %s\n' "$1"; rc=1; fi; }
  check "added file copied in full"            "[ \"\$(cat '$out/files/src/b.txt')\" = new ]"
  check "modified file copied post-change"     "grep -q TWO '$out/files/src/a.txt'"
  check "summarised file NOT copied"           "[ ! -e '$out/files/i18n/de/x.md' ]"
  check "expanded hunk present in diff.md"     "grep -q '^+TWO' '$out/diff.md'"
  check "summarised path in stat"              "grep -q 'i18n/de/x.md' '$out/diff.md'"
  check "summarised hunk only in the sample"   "[ \"\$(grep -c '^+mirror-changed' '$out/diff.md')\" = 1 ]"
  check "README forbids reading the tree"      "grep -q 'Do NOT read the repository working tree' '$out/README.md'"
  check "README lists the bundle"              "grep -q './files/src/b.txt' '$out/README.md'"
  # negative control: the tool must refuse, with exit 2, when there is nothing to bundle
  local rc2
  (cd "$repo" && git checkout -q base && bash "$SELF" --base base --out "$tmp/empty" >/dev/null 2>&1); rc2=$?
  check "no changes → exit 2, never a pass"    "[ $rc2 -eq 2 ]"
  rm -rf "$tmp"
  [ "$rc" -eq 0 ] && printf 'verify: all checks passed\n'
  exit "$rc"
}

case "${1:-}" in
  --verify) verify ;;
  -h|--help) sed -n '2,30p' "$SELF"; exit 0 ;;
  *) build "$@" ;;
esac
